export class Color {
  readonly name: string;
  readonly hex: string;

  constructor(name: string, hex: string) {
    this.name = name;
    this.hex = hex;
  }
}

// Colors copied from: https://chir.ag/projects/name-that-color
export const colors = [
  new Color('Black', '#000000'),
  new Color('Navy Blue', '#000080'),
  new Color('Dark Blue', '#0000c8'),
  new Color('Blue', '#0000ff'),
  new Color('Stratos', '#000741'),
  new Color('Swamp', '#001b1c'),
  new Color('Resolution Blue', '#002387'),
  new Color('Deep Fir', '#002900'),
  new Color('Burnham', '#002e20'),
  new Color('International Klein Blue', '#002fa7'),
  new Color('Prussian Blue', '#003153'),
  new Color('Midnight Blue', '#003366'),
  new Color('Smalt', '#003399'),
  new Color('Deep Teal', '#003532'),
  new Color('Cyprus', '#003e40'),
  new Color('Kaitoke Green', '#004620'),
  new Color('Cobalt', '#0047ab'),
  new Color('Crusoe', '#004816'),
  new Color('Sherpa Blue', '#004950'),
  new Color('Endeavour', '#0056a7'),
  new Color('Camarone', '#00581a'),
  new Color('Science Blue', '#0066cc'),
  new Color('Blue Ribbon', '#0066ff'),
  new Color('Tropical Rain Forest', '#00755e'),
  new Color('Allports', '#0076a3'),
  new Color('Deep Cerulean', '#007ba7'),
  new Color('Lochmara', '#007ec7'),
  new Color('Azure Radiance', '#007fff'),
  new Color('Teal', '#008080'),
  new Color('Bondi Blue', '#0095b6'),
  new Color('Pacific Blue', '#009dc4'),
  new Color('Persian Green', '#00a693'),
  new Color('Jade', '#00a86b'),
  new Color('Caribbean Green', '#00cc99'),
  new Color("Robin's Egg Blue", '#00cccc'),
  new Color('Green', '#00ff00'),
  new Color('Spring Green', '#00ff7f'),
  new Color('Cyan / Aqua', '#00ffff'),
  new Color('Blue Charcoal', '#010d1a'),
  new Color('Midnight', '#011635'),
  new Color('Holly', '#011d13'),
  new Color('Daintree', '#012731'),
  new Color('Cardin Green', '#01361c'),
  new Color('County Green', '#01371a'),
  new Color('Astronaut Blue', '#013e62'),
  new Color('Regal Blue', '#013f6a'),
  new Color('Aqua Deep', '#014b43'),
  new Color('Orient', '#015e85'),
  new Color('Blue Stone', '#016162'),
  new Color('Fun Green', '#016d39'),
  new Color('Pine Green', '#01796f'),
  new Color('Blue Lagoon', '#017987'),
  new Color('Deep Sea', '#01826b'),
  new Color('Green Haze', '#01a368'),
  new Color('English Holly', '#022d15'),
  new Color('Sherwood Green', '#02402c'),
  new Color('Congress Blue', '#02478e'),
  new Color('Evening Sea', '#024e46'),
  new Color('Bahama Blue', '#026395'),
  new Color('Observatory', '#02866f'),
  new Color('Cerulean', '#02a4d3'),
  new Color('Tangaroa', '#03163c'),
  new Color('Green Vogue', '#032b52'),
  new Color('Mosque', '#036a6e'),
  new Color('Midnight Moss', '#041004'),
  new Color('Black Pearl', '#041322'),
  new Color('Blue Whale', '#042e4c'),
  new Color('Zuccini', '#044022'),
  new Color('Teal Blue', '#044259'),
  new Color('Deep Cove', '#051040'),
  new Color('Gulf Blue', '#051657'),
  new Color('Venice Blue', '#055989'),
  new Color('Watercourse', '#056f57'),
  new Color('Catalina Blue', '#062a78'),
  new Color('Tiber', '#063537'),
  new Color('Gossamer', '#069b81'),
  new Color('Niagara', '#06a189'),
  new Color('Tarawera', '#073a50'),
  new Color('Jaguar', '#080110'),
  new Color('Black Bean', '#081910'),
  new Color('Deep Sapphire', '#082567'),
  new Color('Elf Green', '#088370'),
  new Color('Bright Turquoise', '#08e8de'),
  new Color('Downriver', '#092256'),
  new Color('Palm Green', '#09230f'),
  new Color('Madison', '#09255d'),
  new Color('Bottle Green', '#093624'),
  new Color('Deep Sea Green', '#095859'),
  new Color('Salem', '#097f4b'),
  new Color('Black Russian', '#0a001c'),
  new Color('Dark Fern', '#0a480d'),
  new Color('Japanese Laurel', '#0a6906'),
  new Color('Atoll', '#0a6f75'),
  new Color('Cod Gray', '#0b0b0b'),
  new Color('Marshland', '#0b0f08'),
  new Color('Gordons Green', '#0b1107'),
  new Color('Black Forest', '#0b1304'),
  new Color('San Felix', '#0b6207'),
  new Color('Malachite', '#0bda51'),
  new Color('Ebony', '#0c0b1d'),
  new Color('Woodsmoke', '#0c0d0f'),
  new Color('Racing Green', '#0c1911'),
  new Color('Surfie Green', '#0c7a79'),
  new Color('Blue Chill', '#0c8990'),
  new Color('Black Rock', '#0d0332'),
  new Color('Bunker', '#0d1117'),
  new Color('Aztec', '#0d1c19'),
  new Color('Bush', '#0d2e1c'),
  new Color('Cinder', '#0e0e18'),
  new Color('Firefly', '#0e2a30'),
  new Color('Torea Bay', '#0f2d9e'),
  new Color('Vulcan', '#10121d'),
  new Color('Green Waterloo', '#101405'),
  new Color('Eden', '#105852'),
  new Color('Arapawa', '#110c6c'),
  new Color('Ultramarine', '#120a8f'),
  new Color('Elephant', '#123447'),
  new Color('Jewel', '#126b40'),
  new Color('Diesel', '#130000'),
  new Color('Asphalt', '#130a06'),
  new Color('Blue Zodiac', '#13264d'),
  new Color('Parsley', '#134f19'),
  new Color('Nero', '#140600'),
  new Color('Tory Blue', '#1450aa'),
  new Color('Bunting', '#151f4c'),
  new Color('Denim', '#1560bd'),
  new Color('Genoa', '#15736b'),
  new Color('Mirage', '#161928'),
  new Color('Hunter Green', '#161d10'),
  new Color('Big Stone', '#162a40'),
  new Color('Celtic', '#163222'),
  new Color('Timber Green', '#16322c'),
  new Color('Gable Green', '#163531'),
  new Color('Pine Tree', '#171f04'),
  new Color('Chathams Blue', '#175579'),
  new Color('Deep Forest Green', '#182d09'),
  new Color('Blumine', '#18587a'),
  new Color('Palm Leaf', '#19330e'),
  new Color('Nile Blue', '#193751'),
  new Color('Fun Blue', '#1959a8'),
  new Color('Lucky Point', '#1a1a68'),
  new Color('Mountain Meadow', '#1ab385'),
  new Color('Tolopea', '#1b0245'),
  new Color('Haiti', '#1b1035'),
  new Color('Deep Koamaru', '#1b127b'),
  new Color('Acadia', '#1b1404'),
  new Color('Seaweed', '#1b2f11'),
  new Color('Biscay', '#1b3162'),
  new Color('Matisse', '#1b659d'),
  new Color('Crowshead', '#1c1208'),
  new Color('Rangoon Green', '#1c1e13'),
  new Color('Persian Blue', '#1c39bb'),
  new Color('Everglade', '#1c402e'),
  new Color('Elm', '#1c7c7d'),
  new Color('Green Pea', '#1d6142'),
  new Color('Creole', '#1e0f04'),
  new Color('Karaka', '#1e1609'),
  new Color('El Paso', '#1e1708'),
  new Color('Cello', '#1e385b'),
  new Color('Te Papa Green', '#1e433c'),
  new Color('Dodger Blue', '#1e90ff'),
  new Color('Eastern Blue', '#1e9ab0'),
  new Color('Night Rider', '#1f120f'),
  new Color('Java', '#1fc2c2'),
  new Color('Jacksons Purple', '#20208d'),
  new Color('Cloud Burst', '#202e54'),
  new Color('Blue Dianne', '#204852'),
  new Color('Eternity', '#211a0e'),
  new Color('Deep Blue', '#220878'),
  new Color('Forest Green', '#228b22'),
  new Color('Mallard', '#233418'),
  new Color('Violet', '#240a40'),
  new Color('Kilamanjaro', '#240c02'),
  new Color('Log Cabin', '#242a1d'),
  new Color('Black Olive', '#242e16'),
  new Color('Green House', '#24500f'),
  new Color('Graphite', '#251607'),
  new Color('Cannon Black', '#251706'),
  new Color('Port Gore', '#251f4f'),
  new Color('Shark', '#25272c'),
  new Color('Green Kelp', '#25311c'),
  new Color('Curious Blue', '#2596d1'),
  new Color('Paua', '#260368'),
  new Color('Paris M', '#26056a'),
  new Color('Wood Bark', '#261105'),
  new Color('Gondola', '#261414'),
  new Color('Steel Gray', '#262335'),
  new Color('Ebony Clay', '#26283b'),
  new Color('Bay of Many', '#273a81'),
  new Color('Plantation', '#27504b'),
  new Color('Eucalyptus', '#278a5b'),
  new Color('Oil', '#281e15'),
  new Color('Astronaut', '#283a77'),
  new Color('Mariner', '#286acd'),
  new Color('Violent Violet', '#290c5e'),
  new Color('Bastille', '#292130'),
  new Color('Zeus', '#292319'),
  new Color('Charade', '#292937'),
  new Color('Jelly Bean', '#297b9a'),
  new Color('Jungle Green', '#29ab87'),
  new Color('Cherry Pie', '#2a0359'),
  new Color('Coffee Bean', '#2a140e'),
  new Color('Baltic Sea', '#2a2630'),
  new Color('Turtle Green', '#2a380b'),
  new Color('Cerulean Blue', '#2a52be'),
  new Color('Sepia Black', '#2b0202'),
  new Color('Valhalla', '#2b194f'),
  new Color('Heavy Metal', '#2b3228'),
  new Color('Blue Gem', '#2c0e8c'),
  new Color('Revolver', '#2c1632'),
  new Color('Bleached Cedar', '#2c2133'),
  new Color('Lochinvar', '#2c8c84'),
  new Color('Mikado', '#2d2510'),
  new Color('Outer Space', '#2d383a'),
  new Color('St Tropaz', '#2d569b'),
  new Color('Jacaranda', '#2e0329'),
  new Color('Jacko Bean', '#2e1905'),
  new Color('Rangitoto', '#2e3222'),
  new Color('Rhino', '#2e3f62'),
  new Color('Sea Green', '#2e8b57'),
  new Color('Scooter', '#2ebfd4'),
  new Color('Onion', '#2f270e'),
  new Color('Governor Bay', '#2f3cb3'),
  new Color('Sapphire', '#2f519e'),
  new Color('Spectra', '#2f5a57'),
  new Color('Casal', '#2f6168'),
  new Color('Melanzane', '#300529'),
  new Color('Cocoa Brown', '#301f1e'),
  new Color('Woodrush', '#302a0f'),
  new Color('San Juan', '#304b6a'),
  new Color('Turquoise', '#30d5c8'),
  new Color('Eclipse', '#311c17'),
  new Color('Pickled Bluewood', '#314459'),
  new Color('Azure', '#315ba1'),
  new Color('Calypso', '#31728d'),
  new Color('Paradiso', '#317d82'),
  new Color('Persian Indigo', '#32127a'),
  new Color('Blackcurrant', '#32293a'),
  new Color('Mine Shaft', '#323232'),
  new Color('Stromboli', '#325d52'),
  new Color('Bilbao', '#327c14'),
  new Color('Astral', '#327da0'),
  new Color('Christalle', '#33036b'),
  new Color('Thunder', '#33292f'),
  new Color('Shamrock', '#33cc99'),
  new Color('Tamarind', '#341515'),
  new Color('Mardi Gras', '#350036'),
  new Color('Valentino', '#350e42'),
  new Color('Jagger', '#350e57'),
  new Color('Tuna', '#353542'),
  new Color('Chambray', '#354e8c'),
  new Color('Martinique', '#363050'),
  new Color('Tuatara', '#363534'),
  new Color('Waiouru', '#363c0d'),
  new Color('Ming', '#36747d'),
  new Color('La Palma', '#368716'),
  new Color('Chocolate', '#370202'),
  new Color('Clinker', '#371d09'),
  new Color('Brown Tumbleweed', '#37290e'),
  new Color('Birch', '#373021'),
  new Color('Oracle', '#377475'),
  new Color('Blue Diamond', '#380474'),
  new Color('Grape', '#381a51'),
  new Color('Dune', '#383533'),
  new Color('Oxford Blue', '#384555'),
  new Color('Clover', '#384910'),
  new Color('Limed Spruce', '#394851'),
  new Color('Dell', '#396413'),
  new Color('Toledo', '#3a0020'),
  new Color('Sambuca', '#3a2010'),
  new Color('Jacarta', '#3a2a6a'),
  new Color('William', '#3a686c'),
  new Color('Killarney', '#3a6a47'),
  new Color('Keppel', '#3ab09e'),
  new Color('Temptress', '#3b000b'),
  new Color('Aubergine', '#3b0910'),
  new Color('Jon', '#3b1f1f'),
  new Color('Treehouse', '#3b2820'),
  new Color('Amazon', '#3b7a57'),
  new Color('Boston Blue', '#3b91b4'),
  new Color('Windsor', '#3c0878'),
  new Color('Rebel', '#3c1206'),
  new Color('Meteorite', '#3c1f76'),
  new Color('Dark Ebony', '#3c2005'),
  new Color('Camouflage', '#3c3910'),
  new Color('Bright Gray', '#3c4151'),
  new Color('Cape Cod', '#3c4443'),
  new Color('Lunar Green', '#3c493a'),
  new Color('Bean  ', '#3d0c02'),
  new Color('Bistre', '#3d2b1f'),
  new Color('Goblin', '#3d7d52'),
  new Color('Kingfisher Daisy', '#3e0480'),
  new Color('Cedar', '#3e1c14'),
  new Color('English Walnut', '#3e2b23'),
  new Color('Black Marlin', '#3e2c1c'),
  new Color('Ship Gray', '#3e3a44'),
  new Color('Pelorous', '#3eabbf'),
  new Color('Bronze', '#3f2109'),
  new Color('Cola', '#3f2500'),
  new Color('Madras', '#3f3002'),
  new Color('Minsk', '#3f307f'),
  new Color('Cabbage Pont', '#3f4c3a'),
  new Color('Tom Thumb', '#3f583b'),
  new Color('Mineral Green', '#3f5d53'),
  new Color('Puerto Rico', '#3fc1aa'),
  new Color('Harlequin', '#3fff00'),
  new Color('Brown Pod', '#401801'),
  new Color('Cork', '#40291d'),
  new Color('Masala', '#403b38'),
  new Color('Thatch Green', '#403d19'),
  new Color('Fiord', '#405169'),
  new Color('Viridian', '#40826d'),
  new Color('Chateau Green', '#40a860'),
  new Color('Ripe Plum', '#410056'),
  new Color('Paco', '#411f10'),
  new Color('Deep Oak', '#412010'),
  new Color('Merlin', '#413c37'),
  new Color('Gun Powder', '#414257'),
  new Color('East Bay', '#414c7d'),
  new Color('Royal Blue', '#4169e1'),
  new Color('Ocean Green', '#41aa78'),
  new Color('Burnt Maroon', '#420303'),
  new Color('Lisbon Brown', '#423921'),
  new Color('Faded Jade', '#427977'),
  new Color('Scarlet Gum', '#431560'),
  new Color('Iroko', '#433120'),
  new Color('Armadillo', '#433e37'),
  new Color('River Bed', '#434c59'),
  new Color('Green Leaf', '#436a0d'),
  new Color('Barossa', '#44012d'),
  new Color('Morocco Brown', '#441d00'),
  new Color('Mako', '#444954'),
  new Color('Kelp', '#454936'),
  new Color('San Marino', '#456cac'),
  new Color('Picton Blue', '#45b1e8'),
  new Color('Loulou', '#460b41'),
  new Color('Crater Brown', '#462425'),
  new Color('Gray Asparagus', '#465945'),
  new Color('Steel Blue', '#4682b4'),
  new Color('Rustic Red', '#480404'),
  new Color('Bulgarian Rose', '#480607'),
  new Color('Clairvoyant', '#480656'),
  new Color('Cocoa Bean', '#481c1c'),
  new Color('Woody Brown', '#483131'),
  new Color('Taupe', '#483c32'),
  new Color('Van Cleef', '#49170c'),
  new Color('Brown Derby', '#492615'),
  new Color('Metallic Bronze', '#49371b'),
  new Color('Verdun Green', '#495400'),
  new Color('Blue Bayoux', '#496679'),
  new Color('Bismark', '#497183'),
  new Color('Bracken', '#4a2a04'),
  new Color('Deep Bronze', '#4a3004'),
  new Color('Mondo', '#4a3c30'),
  new Color('Tundora', '#4a4244'),
  new Color('Gravel', '#4a444b'),
  new Color('Trout', '#4a4e5a'),
  new Color('Pigment Indigo', '#4b0082'),
  new Color('Nandor', '#4b5d52'),
  new Color('Saddle', '#4c3024'),
  new Color('Abbey', '#4c4f56'),
  new Color('Blackberry', '#4d0135'),
  new Color('Cab Sav', '#4d0a18'),
  new Color('Indian Tan', '#4d1e01'),
  new Color('Cowboy', '#4d282d'),
  new Color('Livid Brown', '#4d282e'),
  new Color('Rock', '#4d3833'),
  new Color('Punga', '#4d3d14'),
  new Color('Bronzetone', '#4d400f'),
  new Color('Woodland', '#4d5328'),
  new Color('Mahogany', '#4e0606'),
  new Color('Bossanova', '#4e2a5a'),
  new Color('Matterhorn', '#4e3b41'),
  new Color('Bronze Olive', '#4e420c'),
  new Color('Mulled Wine', '#4e4562'),
  new Color('Axolotl', '#4e6649'),
  new Color('Wedgewood', '#4e7f9e'),
  new Color('Shakespeare', '#4eabd1'),
  new Color('Honey Flower', '#4f1c70'),
  new Color('Daisy Bush', '#4f2398'),
  new Color('Indigo', '#4f69c6'),
  new Color('Fern Green', '#4f7942'),
  new Color('Fruit Salad', '#4f9d5d'),
  new Color('Apple', '#4fa83d'),
  new Color('Mortar', '#504351'),
  new Color('Kashmir Blue', '#507096'),
  new Color('Cutty Sark', '#507672'),
  new Color('Emerald', '#50c878'),
  new Color('Emperor', '#514649'),
  new Color('Chalet Green', '#516e3d'),
  new Color('Como', '#517c66'),
  new Color('Smalt Blue', '#51808f'),
  new Color('Castro', '#52001f'),
  new Color('Maroon Oak', '#520c17'),
  new Color('Gigas', '#523c94'),
  new Color('Voodoo', '#533455'),
  new Color('Victoria', '#534491'),
  new Color('Hippie Green', '#53824b'),
  new Color('Heath', '#541012'),
  new Color('Judge Gray', '#544333'),
  new Color('Fuscous Gray', '#54534d'),
  new Color('Vida Loca', '#549019'),
  new Color('Cioccolato', '#55280c'),
  new Color('Saratoga', '#555b10'),
  new Color('Finlandia', '#556d56'),
  new Color('Havelock Blue', '#5590d9'),
  new Color('Fountain Blue', '#56b4be'),
  new Color('Spring Leaves', '#578363'),
  new Color('Saddle Brown', '#583401'),
  new Color('Scarpa Flow', '#585562'),
  new Color('Cactus', '#587156'),
  new Color('Hippie Blue', '#589aaf'),
  new Color('Wine Berry', '#591d35'),
  new Color('Brown Bramble', '#592804'),
  new Color('Congo Brown', '#593737'),
  new Color('Millbrook', '#594433'),
  new Color('Waikawa Gray', '#5a6e9c'),
  new Color('Horizon', '#5a87a0'),
  new Color('Jambalaya', '#5b3013'),
  new Color('Bordeaux', '#5c0120'),
  new Color('Mulberry Wood', '#5c0536'),
  new Color('Carnaby Tan', '#5c2e01'),
  new Color('Comet', '#5c5d75'),
  new Color('Redwood', '#5d1e0f'),
  new Color('Don Juan', '#5d4c51'),
  new Color('Chicago', '#5d5c58'),
  new Color('Verdigris', '#5d5e37'),
  new Color('Dingley', '#5d7747'),
  new Color('Breaker Bay', '#5da19f'),
  new Color('Kabul', '#5e483e'),
  new Color('Hemlock', '#5e5d3b'),
  new Color('Irish Coffee', '#5f3d26'),
  new Color('Mid Gray', '#5f5f6e'),
  new Color('Shuttle Gray', '#5f6672'),
  new Color('Aqua Forest', '#5fa777'),
  new Color('Tradewind', '#5fb3ac'),
  new Color('Horses Neck', '#604913'),
  new Color('Smoky', '#605b73'),
  new Color('Corduroy', '#606e68'),
  new Color('Danube', '#6093d1'),
  new Color('Espresso', '#612718'),
  new Color('Eggplant', '#614051'),
  new Color('Costa Del Sol', '#615d30'),
  new Color('Glade Green', '#61845f'),
  new Color('Buccaneer', '#622f30'),
  new Color('Quincy', '#623f2d'),
  new Color('Butterfly Bush', '#624e9a'),
  new Color('West Coast', '#625119'),
  new Color('Finch', '#626649'),
  new Color('Patina', '#639a8f'),
  new Color('Fern', '#63b76c'),
  new Color('Blue Violet', '#6456b7'),
  new Color('Dolphin', '#646077'),
  new Color('Storm Dust', '#646463'),
  new Color('Siam', '#646a54'),
  new Color('Nevada', '#646e75'),
  new Color('Cornflower Blue', '#6495ed'),
  new Color('Viking', '#64ccdb'),
  new Color('Rosewood', '#65000b'),
  new Color('Cherrywood', '#651a14'),
  new Color('Purple Heart', '#652dc1'),
  new Color('Fern Frond', '#657220'),
  new Color('Willow Grove', '#65745d'),
  new Color('Hoki', '#65869f'),
  new Color('Pompadour', '#660045'),
  new Color('Purple', '#660099'),
  new Color('Tyrian Purple', '#66023c'),
  new Color('Dark Tan', '#661010'),
  new Color('Silver Tree', '#66b58f'),
  new Color('Bright Green', '#66ff00'),
  new Color("Screamin' Green", '#66ff66'),
  new Color('Black Rose', '#67032d'),
  new Color('Scampi', '#675fa6'),
  new Color('Ironside Gray', '#676662'),
  new Color('Viridian Green', '#678975'),
  new Color('Christi', '#67a712'),
  new Color('Nutmeg Wood Finish', '#683600'),
  new Color('Zambezi', '#685558'),
  new Color('Salt Box', '#685e6e'),
  new Color('Tawny Port', '#692545'),
  new Color('Finn', '#692d54'),
  new Color('Scorpion', '#695f62'),
  new Color('Lynch', '#697e9a'),
  new Color('Spice', '#6a442e'),
  new Color('Himalaya', '#6a5d1b'),
  new Color('Soya Bean', '#6a6051'),
  new Color('Hairy Heath', '#6b2a14'),
  new Color('Royal Purple', '#6b3fa0'),
  new Color('Shingle Fawn', '#6b4e31'),
  new Color('Dorado', '#6b5755'),
  new Color('Bermuda Gray', '#6b8ba2'),
  new Color('Olive Drab', '#6b8e23'),
  new Color('Eminence', '#6c3082'),
  new Color('Turquoise Blue', '#6cdae7'),
  new Color('Lonestar', '#6d0101'),
  new Color('Pine Cone', '#6d5e54'),
  new Color('Dove Gray', '#6d6c6c'),
  new Color('Juniper', '#6d9292'),
  new Color('Gothic', '#6d92a1'),
  new Color('Red Oxide', '#6e0902'),
  new Color('Moccaccino', '#6e1d14'),
  new Color('Pickled Bean', '#6e4826'),
  new Color('Dallas', '#6e4b26'),
  new Color('Kokoda', '#6e6d57'),
  new Color('Pale Sky', '#6e7783'),
  new Color('Cafe Royale', '#6f440c'),
  new Color('Flint', '#6f6a61'),
  new Color('Highland', '#6f8e63'),
  new Color('Limeade', '#6f9d02'),
  new Color('Downy', '#6fd0c5'),
  new Color('Persian Plum', '#701c1c'),
  new Color('Sepia', '#704214'),
  new Color('Antique Bronze', '#704a07'),
  new Color('Ferra', '#704f50'),
  new Color('Coffee', '#706555'),
  new Color('Slate Gray', '#708090'),
  new Color('Cedar Wood Finish', '#711a00'),
  new Color('Metallic Copper', '#71291d'),
  new Color('Affair', '#714693'),
  new Color('Studio', '#714ab2'),
  new Color('Tobacco Brown', '#715d47'),
  new Color('Yellow Metal', '#716338'),
  new Color('Peat', '#716b56'),
  new Color('Olivetone', '#716e10'),
  new Color('Storm Gray', '#717486'),
  new Color('Sirocco', '#718080'),
  new Color('Aquamarine Blue', '#71d9e2'),
  new Color('Venetian Red', '#72010f'),
  new Color('Old Copper', '#724a2f'),
  new Color('Go Ben', '#726d4e'),
  new Color('Raven', '#727b89'),
  new Color('Seance', '#731e8f'),
  new Color('Raw Umber', '#734a12'),
  new Color('Kimberly', '#736c9f'),
  new Color('Crocodile', '#736d58'),
  new Color('Crete', '#737829'),
  new Color('Xanadu', '#738678'),
  new Color('Spicy Mustard', '#74640d'),
  new Color('Limed Ash', '#747d63'),
  new Color('Rolling Stone', '#747d83'),
  new Color('Blue Smoke', '#748881'),
  new Color('Laurel', '#749378'),
  new Color('Mantis', '#74c365'),
  new Color('Russett', '#755a57'),
  new Color('Deluge', '#7563a8'),
  new Color('Cosmic', '#76395d'),
  new Color('Blue Marguerite', '#7666c6'),
  new Color('Lima', '#76bd17'),
  new Color('Sky Blue', '#76d7ea'),
  new Color('Dark Burgundy', '#770f05'),
  new Color('Crown of Thorns', '#771f1f'),
  new Color('Walnut', '#773f1a'),
  new Color('Pablo', '#776f61'),
  new Color('Pacifika', '#778120'),
  new Color('Oxley', '#779e86'),
  new Color('Pastel Green', '#77dd77'),
  new Color('Japanese Maple', '#780109'),
  new Color('Mocha', '#782d19'),
  new Color('Peanut', '#782f16'),
  new Color('Camouflage Green', '#78866b'),
  new Color('Wasabi', '#788a25'),
  new Color('Ship Cove', '#788bba'),
  new Color('Sea Nymph', '#78a39c'),
  new Color('Roman Coffee', '#795d4c'),
  new Color('Old Lavender', '#796878'),
  new Color('Rum', '#796989'),
  new Color('Fedora', '#796a78'),
  new Color('Sandstone', '#796d62'),
  new Color('Spray', '#79deec'),
  new Color('Siren', '#7a013a'),
  new Color('Fuchsia Blue', '#7a58c1'),
  new Color('Boulder', '#7a7a7a'),
  new Color('Wild Blue Yonder', '#7a89b8'),
  new Color('De York', '#7ac488'),
  new Color('Red Beech', '#7b3801'),
  new Color('Cinnamon', '#7b3f00'),
  new Color('Yukon Gold', '#7b6608'),
  new Color('Tapa', '#7b7874'),
  new Color('Waterloo ', '#7b7c94'),
  new Color('Flax Smoke', '#7b8265'),
  new Color('Amulet', '#7b9f80'),
  new Color('Asparagus', '#7ba05b'),
  new Color('Kenyan Copper', '#7c1c05'),
  new Color('Pesto', '#7c7631'),
  new Color('Topaz', '#7c778a'),
  new Color('Concord', '#7c7b7a'),
  new Color('Jumbo', '#7c7b82'),
  new Color('Trendy Green', '#7c881a'),
  new Color('Gumbo', '#7ca1a6'),
  new Color('Acapulco', '#7cb0a1'),
  new Color('Neptune', '#7cb7bb'),
  new Color('Pueblo', '#7d2c14'),
  new Color('Bay Leaf', '#7da98d'),
  new Color('Malibu', '#7dc8f7'),
  new Color('Bermuda', '#7dd8c6'),
  new Color('Copper Canyon', '#7e3a15'),
  new Color('Claret', '#7f1734'),
  new Color('Peru Tan', '#7f3a02'),
  new Color('Falcon', '#7f626d'),
  new Color('Mobster', '#7f7589'),
  new Color('Moody Blue', '#7f76d3'),
  new Color('Chartreuse', '#7fff00'),
  new Color('Aquamarine', '#7fffd4'),
  new Color('Maroon', '#800000'),
  new Color('Rose Bud Cherry', '#800b47'),
  new Color('Falu Red', '#801818'),
  new Color('Red Robin', '#80341f'),
  new Color('Vivid Violet', '#803790'),
  new Color('Russet', '#80461b'),
  new Color('Friar Gray', '#807e79'),
  new Color('Olive', '#808000'),
  new Color('Gray', '#808080'),
  new Color('Gulf Stream', '#80b3ae'),
  new Color('Glacier', '#80b3c4'),
  new Color('Seagull', '#80ccea'),
  new Color('Nutmeg', '#81422c'),
  new Color('Spicy Pink', '#816e71'),
  new Color('Empress', '#817377'),
  new Color('Spanish Green', '#819885'),
  new Color('Sand Dune', '#826f65'),
  new Color('Gunsmoke', '#828685'),
  new Color('Battleship Gray', '#828f72'),
  new Color('Merlot', '#831923'),
  new Color('Shadow', '#837050'),
  new Color('Chelsea Cucumber', '#83aa5d'),
  new Color('Monte Carlo', '#83d0c6'),
  new Color('Plum', '#843179'),
  new Color('Granny Smith', '#84a0a0'),
  new Color('Chetwode Blue', '#8581d9'),
  new Color('Bandicoot', '#858470'),
  new Color('Bali Hai', '#859faf'),
  new Color('Half Baked', '#85c4cc'),
  new Color('Red Devil', '#860111'),
  new Color('Lotus', '#863c3c'),
  new Color('Ironstone', '#86483c'),
  new Color('Bull Shot', '#864d1e'),
  new Color('Rusty Nail', '#86560a'),
  new Color('Bitter', '#868974'),
  new Color('Regent Gray', '#86949f'),
  new Color('Disco', '#871550'),
  new Color('Americano', '#87756e'),
  new Color('Hurricane', '#877c7b'),
  new Color('Oslo Gray', '#878d91'),
  new Color('Sushi', '#87ab39'),
  new Color('Spicy Mix', '#885342'),
  new Color('Kumera', '#886221'),
  new Color('Suva Gray', '#888387'),
  new Color('Avocado', '#888d65'),
  new Color('Camelot', '#893456'),
  new Color('Solid Pink', '#893843'),
  new Color('Cannon Pink', '#894367'),
  new Color('Makara', '#897d6d'),
  new Color('Burnt Umber', '#8a3324'),
  new Color('True V', '#8a73d6'),
  new Color('Clay Creek', '#8a8360'),
  new Color('Monsoon', '#8a8389'),
  new Color('Stack', '#8a8f8a'),
  new Color('Jordy Blue', '#8ab9f1'),
  new Color('Electric Violet', '#8b00ff'),
  new Color('Monarch', '#8b0723'),
  new Color('Corn Harvest', '#8b6b0b'),
  new Color('Olive Haze', '#8b8470'),
  new Color('Schooner', '#8b847e'),
  new Color('Natural Gray', '#8b8680'),
  new Color('Mantle', '#8b9c90'),
  new Color('Portage', '#8b9fee'),
  new Color('Envy', '#8ba690'),
  new Color('Cascade', '#8ba9a5'),
  new Color('Riptide', '#8be6d8'),
  new Color('Cardinal Pink', '#8c055e'),
  new Color('Mule Fawn', '#8c472f'),
  new Color('Potters Clay', '#8c5738'),
  new Color('Trendy Pink', '#8c6495'),
  new Color('Paprika', '#8d0226'),
  new Color('Sanguine Brown', '#8d3d38'),
  new Color('Tosca', '#8d3f3f'),
  new Color('Cement', '#8d7662'),
  new Color('Granite Green', '#8d8974'),
  new Color('Manatee', '#8d90a1'),
  new Color('Polo Blue', '#8da8cc'),
  new Color('Red Berry', '#8e0000'),
  new Color('Rope', '#8e4d1e'),
  new Color('Opium', '#8e6f70'),
  new Color('Domino', '#8e775e'),
  new Color('Mamba', '#8e8190'),
  new Color('Nepal', '#8eabc1'),
  new Color('Pohutukawa', '#8f021c'),
  new Color('El Salva', '#8f3e33'),
  new Color('Korma', '#8f4b0e'),
  new Color('Squirrel', '#8f8176'),
  new Color('Vista Blue', '#8fd6b4'),
  new Color('Burgundy', '#900020'),
  new Color('Old Brick', '#901e1e'),
  new Color('Hemp', '#907874'),
  new Color('Almond Frost', '#907b71'),
  new Color('Sycamore', '#908d39'),
  new Color('Sangria', '#92000a'),
  new Color('Cumin', '#924321'),
  new Color('Beaver', '#926f5b'),
  new Color('Stonewall', '#928573'),
  new Color('Venus', '#928590'),
  new Color('Medium Purple', '#9370db'),
  new Color('Cornflower', '#93ccea'),
  new Color('Algae Green', '#93dfb8'),
  new Color('Copper Rust', '#944747'),
  new Color('Arrowtown', '#948771'),
  new Color('Scarlett', '#950015'),
  new Color('Strikemaster', '#956387'),
  new Color('Mountain Mist', '#959396'),
  new Color('Carmine', '#960018'),
  new Color('Brown', '#964b00'),
  new Color('Leather', '#967059'),
  new Color("Purple Mountain's Majesty", '#9678b6'),
  new Color('Lavender Purple', '#967bb6'),
  new Color('Pewter', '#96a8a1'),
  new Color('Summer Green', '#96bbab'),
  new Color('Au Chico', '#97605d'),
  new Color('Wisteria', '#9771b5'),
  new Color('Atlantis', '#97cd2d'),
  new Color('Vin Rouge', '#983d61'),
  new Color('Lilac Bush', '#9874d3'),
  new Color('Bazaar', '#98777b'),
  new Color('Hacienda', '#98811b'),
  new Color('Pale Oyster', '#988d77'),
  new Color('Mint Green', '#98ff98'),
  new Color('Fresh Eggplant', '#990066'),
  new Color('Violet Eggplant', '#991199'),
  new Color('Tamarillo', '#991613'),
  new Color('Totem Pole', '#991b07'),
  new Color('Copper Rose', '#996666'),
  new Color('Amethyst', '#9966cc'),
  new Color('Mountbatten Pink', '#997a8d'),
  new Color('Blue Bell', '#9999cc'),
  new Color('Prairie Sand', '#9a3820'),
  new Color('Toast', '#9a6e61'),
  new Color('Gurkha', '#9a9577'),
  new Color('Olivine', '#9ab973'),
  new Color('Shadow Green', '#9ac2b8'),
  new Color('Oregon', '#9b4703'),
  new Color('Lemon Grass', '#9b9e8f'),
  new Color('Stiletto', '#9c3336'),
  new Color('Hawaiian Tan', '#9d5616'),
  new Color('Gull Gray', '#9dacb7'),
  new Color('Pistachio', '#9dc209'),
  new Color('Granny Smith Apple', '#9de093'),
  new Color('Anakiwa', '#9de5ff'),
  new Color('Chelsea Gem', '#9e5302'),
  new Color('Sepia Skin', '#9e5b40'),
  new Color('Sage', '#9ea587'),
  new Color('Citron', '#9ea91f'),
  new Color('Rock Blue', '#9eb1cd'),
  new Color('Morning Glory', '#9edee0'),
  new Color('Cognac', '#9f381d'),
  new Color('Reef Gold', '#9f821c'),
  new Color('Star Dust', '#9f9f9c'),
  new Color('Santas Gray', '#9fa0b1'),
  new Color('Sinbad', '#9fd7d3'),
  new Color('Feijoa', '#9fdd8c'),
  new Color('Tabasco', '#a02712'),
  new Color('Buttered Rum', '#a1750d'),
  new Color('Hit Gray', '#a1adb5'),
  new Color('Citrus', '#a1c50a'),
  new Color('Aqua Island', '#a1dad7'),
  new Color('Water Leaf', '#a1e9de'),
  new Color('Flirt', '#a2006d'),
  new Color('Rouge', '#a23b6c'),
  new Color('Cape Palliser', '#a26645'),
  new Color('Gray Chateau', '#a2aab3'),
  new Color('Edward', '#a2aeab'),
  new Color('Pharlap', '#a3807b'),
  new Color('Amethyst Smoke', '#a397b4'),
  new Color('Blizzard Blue', '#a3e3ed'),
  new Color('Delta', '#a4a49d'),
  new Color('Wistful', '#a4a6d3'),
  new Color('Green Smoke', '#a4af6e'),
  new Color('Jazzberry Jam', '#a50b5e'),
  new Color('Zorba', '#a59b91'),
  new Color('Bahia', '#a5cb0c'),
  new Color('Roof Terracotta', '#a62f20'),
  new Color('Paarl', '#a65529'),
  new Color('Barley Corn', '#a68b5b'),
  new Color('Donkey Brown', '#a69279'),
  new Color('Dawn', '#a6a29a'),
  new Color('Mexican Red', '#a72525'),
  new Color('Luxor Gold', '#a7882c'),
  new Color('Rich Gold', '#a85307'),
  new Color('Reno Sand', '#a86515'),
  new Color('Coral Tree', '#a86b6b'),
  new Color('Dusty Gray', '#a8989b'),
  new Color('Dull Lavender', '#a899e6'),
  new Color('Tallow', '#a8a589'),
  new Color('Bud', '#a8ae9c'),
  new Color('Locust', '#a8af8e'),
  new Color('Norway', '#a8bd9f'),
  new Color('Chinook', '#a8e3bd'),
  new Color('Gray Olive', '#a9a491'),
  new Color('Aluminium', '#a9acb6'),
  new Color('Cadet Blue', '#a9b2c3'),
  new Color('Schist', '#a9b497'),
  new Color('Tower Gray', '#a9bdbf'),
  new Color('Perano', '#a9bef2'),
  new Color('Opal', '#a9c6c2'),
  new Color('Night Shadz', '#aa375a'),
  new Color('Fire', '#aa4203'),
  new Color('Muesli', '#aa8b5b'),
  new Color('Sandal', '#aa8d6f'),
  new Color('Shady Lady', '#aaa5a9'),
  new Color('Logan', '#aaa9cd'),
  new Color('Spun Pearl', '#aaabb7'),
  new Color('Regent St Blue', '#aad6e6'),
  new Color('Magic Mint', '#aaf0d1'),
  new Color('Lipstick', '#ab0563'),
  new Color('Royal Heath', '#ab3472'),
  new Color('Sandrift', '#ab917a'),
  new Color('Cold Purple', '#aba0d9'),
  new Color('Bronco', '#aba196'),
  new Color('Limed Oak', '#ac8a56'),
  new Color('East Side', '#ac91ce'),
  new Color('Lemon Ginger', '#ac9e22'),
  new Color('Napa', '#aca494'),
  new Color('Hillary', '#aca586'),
  new Color('Cloudy', '#aca59f'),
  new Color('Silver Chalice', '#acacac'),
  new Color('Swamp Green', '#acb78e'),
  new Color('Spring Rain', '#accbb1'),
  new Color('Conifer', '#acdd4d'),
  new Color('Celadon', '#ace1af'),
  new Color('Mandalay', '#ad781b'),
  new Color('Casper', '#adbed1'),
  new Color('Moss Green', '#addfad'),
  new Color('Padua', '#ade6c4'),
  new Color('Green Yellow', '#adff2f'),
  new Color('Hippie Pink', '#ae4560'),
  new Color('Desert', '#ae6020'),
  new Color('Bouquet', '#ae809e'),
  new Color('Medium Carmine', '#af4035'),
  new Color('Apple Blossom', '#af4d43'),
  new Color('Brown Rust', '#af593e'),
  new Color('Driftwood', '#af8751'),
  new Color('Alpine', '#af8f2c'),
  new Color('Lucky', '#af9f1c'),
  new Color('Martini', '#afa09e'),
  new Color('Bombay', '#afb1b8'),
  new Color('Pigeon Post', '#afbdd9'),
  new Color('Cadillac', '#b04c6a'),
  new Color('Matrix', '#b05d54'),
  new Color('Tapestry', '#b05e81'),
  new Color('Mai Tai', '#b06608'),
  new Color('Del Rio', '#b09a95'),
  new Color('Powder Blue', '#b0e0e6'),
  new Color('Inch Worm', '#b0e313'),
  new Color('Bright Red', '#b10000'),
  new Color('Vesuvius', '#b14a0b'),
  new Color('Pumpkin Skin', '#b1610b'),
  new Color('Santa Fe', '#b16d52'),
  new Color('Teak', '#b19461'),
  new Color('Fringy Flower', '#b1e2c1'),
  new Color('Ice Cold', '#b1f4e7'),
  new Color('Shiraz', '#b20931'),
  new Color('Biloba Flower', '#b2a1ea'),
  new Color('Tall Poppy', '#b32d29'),
  new Color('Fiery Orange', '#b35213'),
  new Color('Hot Toddy', '#b38007'),
  new Color('Taupe Gray', '#b3af95'),
  new Color('La Rioja', '#b3c110'),
  new Color('Well Read', '#b43332'),
  new Color('Blush', '#b44668'),
  new Color('Jungle Mist', '#b4cfd3'),
  new Color('Turkish Rose', '#b57281'),
  new Color('Lavender', '#b57edc'),
  new Color('Mongoose', '#b5a27f'),
  new Color('Olive Green', '#b5b35c'),
  new Color('Jet Stream', '#b5d2ce'),
  new Color('Cruise', '#b5ecdf'),
  new Color('Hibiscus', '#b6316c'),
  new Color('Thatch', '#b69d98'),
  new Color('Heathered Gray', '#b6b095'),
  new Color('Eagle', '#b6baa4'),
  new Color('Spindle', '#b6d1ea'),
  new Color('Gum Leaf', '#b6d3bf'),
  new Color('Rust', '#b7410e'),
  new Color('Muddy Waters', '#b78e5c'),
  new Color('Sahara', '#b7a214'),
  new Color('Husk', '#b7a458'),
  new Color('Nobel', '#b7b1b1'),
  new Color('Heather', '#b7c3d0'),
  new Color('Madang', '#b7f0be'),
  new Color('Milano Red', '#b81104'),
  new Color('Copper', '#b87333'),
  new Color('Gimblet', '#b8b56a'),
  new Color('Green Spring', '#b8c1b1'),
  new Color('Celery', '#b8c25d'),
  new Color('Sail', '#b8e0f9'),
  new Color('Chestnut', '#b94e48'),
  new Color('Crail', '#b95140'),
  new Color('Marigold', '#b98d28'),
  new Color('Wild Willow', '#b9c46a'),
  new Color('Rainee', '#b9c8ac'),
  new Color('Guardsman Red', '#ba0101'),
  new Color('Rock Spray', '#ba450c'),
  new Color('Bourbon', '#ba6f1e'),
  new Color('Pirate Gold', '#ba7f03'),
  new Color('Nomad', '#bab1a2'),
  new Color('Submarine', '#bac7c9'),
  new Color('Charlotte', '#baeef9'),
  new Color('Medium Red Violet', '#bb3385'),
  new Color('Brandy Rose', '#bb8983'),
  new Color('Rio Grande', '#bbd009'),
  new Color('Surf', '#bbd7c1'),
  new Color('Powder Ash', '#bcc9c2'),
  new Color('Tuscany', '#bd5e2e'),
  new Color('Quicksand', '#bd978e'),
  new Color('Silk', '#bdb1a8'),
  new Color('Malta', '#bdb2a1'),
  new Color('Chatelle', '#bdb3c7'),
  new Color('Lavender Gray', '#bdbbd7'),
  new Color('French Gray', '#bdbdc6'),
  new Color('Clay Ash', '#bdc8b3'),
  new Color('Loblolly', '#bdc9ce'),
  new Color('French Pass', '#bdedfd'),
  new Color('London Hue', '#bea6c3'),
  new Color('Pink Swan', '#beb5b7'),
  new Color('Fuego', '#bede0d'),
  new Color('Rose of Sharon', '#bf5500'),
  new Color('Tide', '#bfb8b0'),
  new Color('Blue Haze', '#bfbed8'),
  new Color('Silver Sand', '#bfc1c2'),
  new Color('Key Lime Pie', '#bfc921'),
  new Color('Ziggurat', '#bfdbe2'),
  new Color('Lime', '#bfff00'),
  new Color('Thunderbird', '#c02b18'),
  new Color('Mojo', '#c04737'),
  new Color('Old Rose', '#c08081'),
  new Color('Silver', '#c0c0c0'),
  new Color('Pale Leaf', '#c0d3b9'),
  new Color('Pixie Green', '#c0d8b6'),
  new Color('Tia Maria', '#c1440e'),
  new Color('Fuchsia Pink', '#c154c1'),
  new Color('Buddha Gold', '#c1a004'),
  new Color('Bison Hide', '#c1b7a4'),
  new Color('Tea', '#c1bab0'),
  new Color('Gray Suit', '#c1becd'),
  new Color('Sprout', '#c1d7b0'),
  new Color('Sulu', '#c1f07c'),
  new Color('Indochine', '#c26b03'),
  new Color('Twine', '#c2955d'),
  new Color('Cotton Seed', '#c2bdb6'),
  new Color('Pumice', '#c2cac4'),
  new Color('Jagged Ice', '#c2e8e5'),
  new Color('Maroon Flush', '#c32148'),
  new Color('Indian Khaki', '#c3b091'),
  new Color('Pale Slate', '#c3bfc1'),
  new Color('Gray Nickel', '#c3c3bd'),
  new Color('Periwinkle Gray', '#c3cde6'),
  new Color('Tiara', '#c3d1d1'),
  new Color('Tropical Blue', '#c3ddf9'),
  new Color('Cardinal', '#c41e3a'),
  new Color('Fuzzy Wuzzy Brown', '#c45655'),
  new Color('Orange Roughy', '#c45719'),
  new Color('Mist Gray', '#c4c4bc'),
  new Color('Coriander', '#c4d0b0'),
  new Color('Mint Tulip', '#c4f4eb'),
  new Color('Mulberry', '#c54b8c'),
  new Color('Nugget', '#c59922'),
  new Color('Tussock', '#c5994b'),
  new Color('Sea Mist', '#c5dbca'),
  new Color('Yellow Green', '#c5e17a'),
  new Color('Brick Red', '#c62d42'),
  new Color('Contessa', '#c6726b'),
  new Color('Oriental Pink', '#c69191'),
  new Color('Roti', '#c6a84b'),
  new Color('Ash', '#c6c3b5'),
  new Color('Kangaroo', '#c6c8bd'),
  new Color('Las Palmas', '#c6e610'),
  new Color('Monza', '#c7031e'),
  new Color('Red Violet', '#c71585'),
  new Color('Coral Reef', '#c7bca2'),
  new Color('Melrose', '#c7c1ff'),
  new Color('Cloud', '#c7c4bf'),
  new Color('Ghost', '#c7c9d5'),
  new Color('Pine Glade', '#c7cd90'),
  new Color('Botticelli', '#c7dde5'),
  new Color('Antique Brass', '#c88a65'),
  new Color('Lilac', '#c8a2c8'),
  new Color('Hokey Pokey', '#c8a528'),
  new Color('Lily', '#c8aabf'),
  new Color('Laser', '#c8b568'),
  new Color('Edgewater', '#c8e3d7'),
  new Color('Piper', '#c96323'),
  new Color('Pizza', '#c99415'),
  new Color('Light Wisteria', '#c9a0dc'),
  new Color('Rodeo Dust', '#c9b29b'),
  new Color('Sundance', '#c9b35b'),
  new Color('Earls Green', '#c9b93b'),
  new Color('Silver Rust', '#c9c0bb'),
  new Color('Conch', '#c9d9d2'),
  new Color('Reef', '#c9ffa2'),
  new Color('Aero Blue', '#c9ffe5'),
  new Color('Flush Mahogany', '#ca3435'),
  new Color('Turmeric', '#cabb48'),
  new Color('Paris White', '#cadcd4'),
  new Color('Bitter Lemon', '#cae00d'),
  new Color('Skeptic', '#cae6da'),
  new Color('Viola', '#cb8fa9'),
  new Color('Foggy Gray', '#cbcab6'),
  new Color('Green Mist', '#cbd3b0'),
  new Color('Nebula', '#cbdbd6'),
  new Color('Persian Red', '#cc3333'),
  new Color('Burnt Orange', '#cc5500'),
  new Color('Ochre', '#cc7722'),
  new Color('Puce', '#cc8899'),
  new Color('Thistle Green', '#cccaa8'),
  new Color('Periwinkle', '#ccccff'),
  new Color('Electric Lime', '#ccff00'),
  new Color('Tenn', '#cd5700'),
  new Color('Chestnut Rose', '#cd5c5c'),
  new Color('Brandy Punch', '#cd8429'),
  new Color('Onahau', '#cdf4ff'),
  new Color('Sorrell Brown', '#ceb98f'),
  new Color('Cold Turkey', '#cebaba'),
  new Color('Yuma', '#cec291'),
  new Color('Chino', '#cec7a7'),
  new Color('Eunry', '#cfa39d'),
  new Color('Old Gold', '#cfb53b'),
  new Color('Tasman', '#cfdccf'),
  new Color('Surf Crest', '#cfe5d2'),
  new Color('Humming Bird', '#cff9f3'),
  new Color('Scandal', '#cffaf4'),
  new Color('Red Stage', '#d05f04'),
  new Color('Hopbush', '#d06da1'),
  new Color('Meteor', '#d07d12'),
  new Color('Perfume', '#d0bef8'),
  new Color('Prelude', '#d0c0e5'),
  new Color('Tea Green', '#d0f0c0'),
  new Color('Geebung', '#d18f1b'),
  new Color('Vanilla', '#d1bea8'),
  new Color('Soft Amber', '#d1c6b4'),
  new Color('Celeste', '#d1d2ca'),
  new Color('Mischka', '#d1d2dd'),
  new Color('Pear', '#d1e231'),
  new Color('Hot Cinnamon', '#d2691e'),
  new Color('Raw Sienna', '#d27d46'),
  new Color('Careys Pink', '#d29eaa'),
  new Color('Tan', '#d2b48c'),
  new Color('Deco', '#d2da97'),
  new Color('Blue Romance', '#d2f6de'),
  new Color('Gossip', '#d2f8b0'),
  new Color('Sisal', '#d3cbba'),
  new Color('Swirl', '#d3cdc5'),
  new Color('Charm', '#d47494'),
  new Color('Clam Shell', '#d4b6af'),
  new Color('Straw', '#d4bf8d'),
  new Color('Akaroa', '#d4c4a8'),
  new Color('Bird Flower', '#d4cd16'),
  new Color('Iron', '#d4d7d9'),
  new Color('Geyser', '#d4dfe2'),
  new Color('Hawkes Blue', '#d4e2fc'),
  new Color('Grenadier', '#d54600'),
  new Color('Can Can', '#d591a4'),
  new Color('Whiskey', '#d59a6f'),
  new Color('Winter Hazel', '#d5d195'),
  new Color('Granny Apple', '#d5f6e3'),
  new Color('My Pink', '#d69188'),
  new Color('Tacha', '#d6c562'),
  new Color('Moon Raker', '#d6cef6'),
  new Color('Quill Gray', '#d6d6d1'),
  new Color('Snowy Mint', '#d6ffdb'),
  new Color('New York Pink', '#d7837f'),
  new Color('Pavlova', '#d7c498'),
  new Color('Fog', '#d7d0ff'),
  new Color('Valencia', '#d84437'),
  new Color('Japonica', '#d87c63'),
  new Color('Thistle', '#d8bfd8'),
  new Color('Maverick', '#d8c2d5'),
  new Color('Foam', '#d8fcfa'),
  new Color('Cabaret', '#d94972'),
  new Color('Burning Sand', '#d99376'),
  new Color('Cameo', '#d9b99b'),
  new Color('Timberwolf', '#d9d6cf'),
  new Color('Tana', '#d9dcc1'),
  new Color('Link Water', '#d9e4f5'),
  new Color('Mabel', '#d9f7ff'),
  new Color('Cerise', '#da3287'),
  new Color('Flame Pea', '#da5b38'),
  new Color('Bamboo', '#da6304'),
  new Color('Red Damask', '#da6a41'),
  new Color('Orchid', '#da70d6'),
  new Color('Copperfield', '#da8a67'),
  new Color('Golden Grass', '#daa520'),
  new Color('Zanah', '#daecd6'),
  new Color('Iceberg', '#daf4f0'),
  new Color('Oyster Bay', '#dafaff'),
  new Color('Cranberry', '#db5079'),
  new Color('Petite Orchid', '#db9690'),
  new Color('Di Serria', '#db995e'),
  new Color('Alto', '#dbdbdb'),
  new Color('Frosted Mint', '#dbfff8'),
  new Color('Crimson', '#dc143c'),
  new Color('Punch', '#dc4333'),
  new Color('Galliano', '#dcb20c'),
  new Color('Blossom', '#dcb4bc'),
  new Color('Wattle', '#dcd747'),
  new Color('Westar', '#dcd9d2'),
  new Color('Moon Mist', '#dcddcc'),
  new Color('Caper', '#dcedb4'),
  new Color('Swans Down', '#dcf0ea'),
  new Color('Swiss Coffee', '#ddd6d5'),
  new Color('White Ice', '#ddf9f1'),
  new Color('Cerise Red', '#de3163'),
  new Color('Roman', '#de6360'),
  new Color('Tumbleweed', '#dea681'),
  new Color('Gold Tips', '#deba13'),
  new Color('Brandy', '#dec196'),
  new Color('Wafer', '#decbc6'),
  new Color('Sapling', '#ded4a4'),
  new Color('Barberry', '#ded717'),
  new Color('Beryl Green', '#dee5c0'),
  new Color('Pattens Blue', '#def5ff'),
  new Color('Heliotrope', '#df73ff'),
  new Color('Apache', '#dfbe6f'),
  new Color('Chenin', '#dfcd6f'),
  new Color('Lola', '#dfcfdb'),
  new Color('Willow Brook', '#dfecda'),
  new Color('Chartreuse Yellow', '#dfff00'),
  new Color('Mauve', '#e0b0ff'),
  new Color('Anzac', '#e0b646'),
  new Color('Harvest Gold', '#e0b974'),
  new Color('Calico', '#e0c095'),
  new Color('Baby Blue', '#e0ffff'),
  new Color('Sunglo', '#e16865'),
  new Color('Equator', '#e1bc64'),
  new Color('Pink Flare', '#e1c0c8'),
  new Color('Periglacial Blue', '#e1e6d6'),
  new Color('Kidnapper', '#e1ead4'),
  new Color('Tara', '#e1f6e8'),
  new Color('Mandy', '#e25465'),
  new Color('Terracotta', '#e2725b'),
  new Color('Golden Bell', '#e28913'),
  new Color('Shocking', '#e292c0'),
  new Color('Dixie', '#e29418'),
  new Color('Light Orchid', '#e29cd2'),
  new Color('Snuff', '#e2d8ed'),
  new Color('Mystic', '#e2ebed'),
  new Color('Apple Green', '#e2f3ec'),
  new Color('Razzmatazz', '#e30b5c'),
  new Color('Alizarin Crimson', '#e32636'),
  new Color('Cinnabar', '#e34234'),
  new Color('Cavern Pink', '#e3bebe'),
  new Color('Peppermint', '#e3f5e1'),
  new Color('Mindaro', '#e3f988'),
  new Color('Deep Blush', '#e47698'),
  new Color('Gamboge', '#e49b0f'),
  new Color('Melanie', '#e4c2d5'),
  new Color('Twilight', '#e4cfde'),
  new Color('Bone', '#e4d1c0'),
  new Color('Sunflower', '#e4d422'),
  new Color('Grain Brown', '#e4d5b7'),
  new Color('Zombie', '#e4d69b'),
  new Color('Frostee', '#e4f6e7'),
  new Color('Snow Flurry', '#e4ffd1'),
  new Color('Amaranth', '#e52b50'),
  new Color('Zest', '#e5841b'),
  new Color('Dust Storm', '#e5ccc9'),
  new Color('Stark White', '#e5d7bd'),
  new Color('Hampton', '#e5d8af'),
  new Color('Bon Jour', '#e5e0e1'),
  new Color('Mercury', '#e5e5e5'),
  new Color('Polar', '#e5f9f6'),
  new Color('Trinidad', '#e64e03'),
  new Color('Gold Sand', '#e6be8a'),
  new Color('Cashmere', '#e6bea5'),
  new Color('Double Spanish White', '#e6d7b9'),
  new Color('Satin Linen', '#e6e4d4'),
  new Color('Harp', '#e6f2ea'),
  new Color('Off Green', '#e6f8f3'),
  new Color('Hint of Green', '#e6ffe9'),
  new Color('Tranquil', '#e6ffff'),
  new Color('Mango Tango', '#e77200'),
  new Color('Christine', '#e7730a'),
  new Color('Tonys Pink', '#e79f8c'),
  new Color('Kobi', '#e79fc4'),
  new Color('Rose Fog', '#e7bcb4'),
  new Color('Corn', '#e7bf05'),
  new Color('Putty', '#e7cd8c'),
  new Color('Gray Nurse', '#e7ece6'),
  new Color('Lily White', '#e7f8ff'),
  new Color('Bubbles', '#e7feff'),
  new Color('Fire Bush', '#e89928'),
  new Color('Shilo', '#e8b9b3'),
  new Color('Pearl Bush', '#e8e0d5'),
  new Color('Green White', '#e8ebe0'),
  new Color('Chrome White', '#e8f1d4'),
  new Color('Gin', '#e8f2eb'),
  new Color('Aqua Squeeze', '#e8f5f2'),
  new Color('Clementine', '#e96e00'),
  new Color('Burnt Sienna', '#e97451'),
  new Color('Tahiti Gold', '#e97c07'),
  new Color('Oyster Pink', '#e9cecd'),
  new Color('Confetti', '#e9d75a'),
  new Color('Ebb', '#e9e3e3'),
  new Color('Ottoman', '#e9f8ed'),
  new Color('Clear Day', '#e9fffd'),
  new Color('Carissma', '#ea88a8'),
  new Color('Porsche', '#eaae69'),
  new Color('Tulip Tree', '#eab33b'),
  new Color('Rob Roy', '#eac674'),
  new Color('Raffia', '#eadab8'),
  new Color('White Rock', '#eae8d4'),
  new Color('Panache', '#eaf6ee'),
  new Color('Solitude', '#eaf6ff'),
  new Color('Aqua Spring', '#eaf9f5'),
  new Color('Dew', '#eafffe'),
  new Color('Apricot', '#eb9373'),
  new Color('Zinnwaldite', '#ebc2af'),
  new Color('Fuel Yellow', '#eca927'),
  new Color('Ronchi', '#ecc54e'),
  new Color('French Lilac', '#ecc7ee'),
  new Color('Just Right', '#eccdb9'),
  new Color('Wild Rice', '#ece090'),
  new Color('Fall Green', '#ecebbd'),
  new Color('Aths Special', '#ecebce'),
  new Color('Starship', '#ecf245'),
  new Color('Red Ribbon', '#ed0a3f'),
  new Color('Tango', '#ed7a1c'),
  new Color('Carrot Orange', '#ed9121'),
  new Color('Sea Pink', '#ed989e'),
  new Color('Tacao', '#edb381'),
  new Color('Desert Sand', '#edc9af'),
  new Color('Pancho', '#edcdab'),
  new Color('Chamois', '#eddcb1'),
  new Color('Primrose', '#edea99'),
  new Color('Frost', '#edf5dd'),
  new Color('Aqua Haze', '#edf5f5'),
  new Color('Zumthor', '#edf6ff'),
  new Color('Narvik', '#edf9f1'),
  new Color('Honeysuckle', '#edfc84'),
  new Color('Lavender Magenta', '#ee82ee'),
  new Color('Beauty Bush', '#eec1be'),
  new Color('Chalky', '#eed794'),
  new Color('Almond', '#eed9c4'),
  new Color('Flax', '#eedc82'),
  new Color('Bizarre', '#eededa'),
  new Color('Double Colonial White', '#eee3ad'),
  new Color('Cararra', '#eeeee8'),
  new Color('Manz', '#eeef78'),
  new Color('Tahuna Sands', '#eef0c8'),
  new Color('Athens Gray', '#eef0f3'),
  new Color('Tusk', '#eef3c3'),
  new Color('Loafer', '#eef4de'),
  new Color('Catskill White', '#eef6f7'),
  new Color('Twilight Blue', '#eefdff'),
  new Color('Jonquil', '#eeff9a'),
  new Color('Rice Flower', '#eeffe2'),
  new Color('Jaffa', '#ef863f'),
  new Color('Gallery', '#efefef'),
  new Color('Porcelain', '#eff2f3'),
  new Color('Mauvelous', '#f091a9'),
  new Color('Golden Dream', '#f0d52d'),
  new Color('Golden Sand', '#f0db7d'),
  new Color('Buff', '#f0dc82'),
  new Color('Prim', '#f0e2ec'),
  new Color('Khaki', '#f0e68c'),
  new Color('Selago', '#f0eefd'),
  new Color('Titan White', '#f0eeff'),
  new Color('Alice Blue', '#f0f8ff'),
  new Color('Feta', '#f0fcea'),
  new Color('Gold Drop', '#f18200'),
  new Color('Wewak', '#f19bab'),
  new Color('Sahara Sand', '#f1e788'),
  new Color('Parchment', '#f1e9d2'),
  new Color('Blue Chalk', '#f1e9ff'),
  new Color('Mint Julep', '#f1eec1'),
  new Color('Seashell', '#f1f1f1'),
  new Color('Saltpan', '#f1f7f2'),
  new Color('Tidal', '#f1ffad'),
  new Color('Chiffon', '#f1ffc8'),
  new Color('Flamingo', '#f2552a'),
  new Color('Tangerine', '#f28500'),
  new Color('Mandys Pink', '#f2c3b2'),
  new Color('Concrete', '#f2f2f2'),
  new Color('Black Squeeze', '#f2fafa'),
  new Color('Pomegranate', '#f34723'),
  new Color('Buttercup', '#f3ad16'),
  new Color('New Orleans', '#f3d69d'),
  new Color('Vanilla Ice', '#f3d9df'),
  new Color('Sidecar', '#f3e7bb'),
  new Color('Dawn Pink', '#f3e9e5'),
  new Color('Wheatfield', '#f3edcf'),
  new Color('Canary', '#f3fb62'),
  new Color('Orinoco', '#f3fbd4'),
  new Color('Carla', '#f3ffd8'),
  new Color('Hollywood Cerise', '#f400a1'),
  new Color('Sandy brown', '#f4a460'),
  new Color('Saffron', '#f4c430'),
  new Color('Ripe Lemon', '#f4d81c'),
  new Color('Janna', '#f4ebd3'),
  new Color('Pampas', '#f4f2ee'),
  new Color('Wild Sand', '#f4f4f4'),
  new Color('Zircon', '#f4f8ff'),
  new Color('Froly', '#f57584'),
  new Color('Cream Can', '#f5c85c'),
  new Color('Manhattan', '#f5c999'),
  new Color('Maize', '#f5d5a0'),
  new Color('Wheat', '#f5deb3'),
  new Color('Sandwisp', '#f5e7a2'),
  new Color('Pot Pourri', '#f5e7e2'),
  new Color('Albescent White', '#f5e9d3'),
  new Color('Soft Peach', '#f5edef'),
  new Color('Ecru White', '#f5f3e5'),
  new Color('Beige', '#f5f5dc'),
  new Color('Golden Fizz', '#f5fb3d'),
  new Color('Australian Mint', '#f5ffbe'),
  new Color('French Rose', '#f64a8a'),
  new Color('Brilliant Rose', '#f653a6'),
  new Color('Illusion', '#f6a4c9'),
  new Color('Merino', '#f6f0e6'),
  new Color('Black Haze', '#f6f7f7'),
  new Color('Spring Sun', '#f6ffdc'),
  new Color('Violet Red', '#f7468a'),
  new Color('Chilean Fire', '#f77703'),
  new Color('Persian Pink', '#f77fbe'),
  new Color('Rajah', '#f7b668'),
  new Color('Azalea', '#f7c8da'),
  new Color('We Peep', '#f7dbe6'),
  new Color('Quarter Spanish White', '#f7f2e1'),
  new Color('Whisper', '#f7f5fa'),
  new Color('Snow Drift', '#f7faf7'),
  new Color('Casablanca', '#f8b853'),
  new Color('Chantilly', '#f8c3df'),
  new Color('Cherub', '#f8d9e9'),
  new Color('Marzipan', '#f8db9d'),
  new Color('Energy Yellow', '#f8dd5c'),
  new Color('Givry', '#f8e4bf'),
  new Color('White Linen', '#f8f0e8'),
  new Color('Magnolia', '#f8f4ff'),
  new Color('Spring Wood', '#f8f6f1'),
  new Color('Coconut Cream', '#f8f7dc'),
  new Color('White Lilac', '#f8f7fc'),
  new Color('Desert Storm', '#f8f8f7'),
  new Color('Texas', '#f8f99c'),
  new Color('Corn Field', '#f8facd'),
  new Color('Mimosa', '#f8fdd3'),
  new Color('Carnation', '#f95a61'),
  new Color('Saffron Mango', '#f9bf58'),
  new Color('Carousel Pink', '#f9e0ed'),
  new Color('Dairy Cream', '#f9e4bc'),
  new Color('Portica', '#f9e663'),
  new Color('Amour', '#f9eaf3'),
  new Color('Rum Swizzle', '#f9f8e4'),
  new Color('Dolly', '#f9ff8b'),
  new Color('Sugar Cane', '#f9fff6'),
  new Color('Ecstasy', '#fa7814'),
  new Color('Tan Hide', '#fa9d5a'),
  new Color('Corvette', '#fad3a2'),
  new Color('Peach Yellow', '#fadfad'),
  new Color('Turbo', '#fae600'),
  new Color('Astra', '#faeab9'),
  new Color('Champagne', '#faeccc'),
  new Color('Linen', '#faf0e6'),
  new Color('Fantasy', '#faf3f0'),
  new Color('Citrine White', '#faf7d6'),
  new Color('Alabaster', '#fafafa'),
  new Color('Hint of Yellow', '#fafde4'),
  new Color('Milan', '#faffa4'),
  new Color('Brink Pink', '#fb607f'),
  new Color('Geraldine', '#fb8989'),
  new Color('Lavender Rose', '#fba0e3'),
  new Color('Sea Buckthorn', '#fba129'),
  new Color('Sun', '#fbac13'),
  new Color('Lavender Pink', '#fbaed2'),
  new Color('Rose Bud', '#fbb2a3'),
  new Color('Cupid', '#fbbeda'),
  new Color('Classic Rose', '#fbcce7'),
  new Color('Apricot Peach', '#fbceb1'),
  new Color('Banana Mania', '#fbe7b2'),
  new Color('Marigold Yellow', '#fbe870'),
  new Color('Festival', '#fbe96c'),
  new Color('Sweet Corn', '#fbea8c'),
  new Color('Candy Corn', '#fbec5d'),
  new Color('Hint of Red', '#fbf9f9'),
  new Color('Shalimar', '#fbffba'),
  new Color('Shocking Pink', '#fc0fc0'),
  new Color('Tickle Me Pink', '#fc80a5'),
  new Color('Tree Poppy', '#fc9c1d'),
  new Color('Lightning Yellow', '#fcc01e'),
  new Color('Goldenrod', '#fcd667'),
  new Color('Candlelight', '#fcd917'),
  new Color('Cherokee', '#fcda98'),
  new Color('Double Pearl Lusta', '#fcf4d0'),
  new Color('Pearl Lusta', '#fcf4dc'),
  new Color('Vista White', '#fcf8f7'),
  new Color('Bianca', '#fcfbf3'),
  new Color('Moon Glow', '#fcfeda'),
  new Color('China Ivory', '#fcffe7'),
  new Color('Ceramic', '#fcfff9'),
  new Color('Torch Red', '#fd0e35'),
  new Color('Wild Watermelon', '#fd5b78'),
  new Color('Crusta', '#fd7b33'),
  new Color('Sorbus', '#fd7c07'),
  new Color('Sweet Pink', '#fd9fa2'),
  new Color('Light Apricot', '#fdd5b1'),
  new Color('Pig Pink', '#fdd7e4'),
  new Color('Cinderella', '#fde1dc'),
  new Color('Golden Glow', '#fde295'),
  new Color('Lemon', '#fde910'),
  new Color('Old Lace', '#fdf5e6'),
  new Color('Half Colonial White', '#fdf6d3'),
  new Color('Drover', '#fdf7ad'),
  new Color('Pale Prim', '#fdfeb8'),
  new Color('Cumulus', '#fdffd5'),
  new Color('Persian Rose', '#fe28a2'),
  new Color('Sunset Orange', '#fe4c40'),
  new Color('Bittersweet', '#fe6f5e'),
  new Color('California', '#fe9d04'),
  new Color('Yellow Sea', '#fea904'),
  new Color('Melon', '#febaad'),
  new Color('Bright Sun', '#fed33c'),
  new Color('Dandelion', '#fed85d'),
  new Color('Salomie', '#fedb8d'),
  new Color('Cape Honey', '#fee5ac'),
  new Color('Remy', '#feebf3'),
  new Color('Oasis', '#feefce'),
  new Color('Bridesmaid', '#fef0ec'),
  new Color('Beeswax', '#fef2c7'),
  new Color('Bleach White', '#fef3d8'),
  new Color('Pipi', '#fef4cc'),
  new Color('Half Spanish White', '#fef4db'),
  new Color('Wisp Pink', '#fef4f8'),
  new Color('Provincial Pink', '#fef5f1'),
  new Color('Half Dutch White', '#fef7de'),
  new Color('Solitaire', '#fef8e2'),
  new Color('White Pointer', '#fef8ff'),
  new Color('Off Yellow', '#fef9e3'),
  new Color('Orange White', '#fefced'),
  new Color('Red', '#ff0000'),
  new Color('Rose', '#ff007f'),
  new Color('Purple Pizzazz', '#ff00cc'),
  new Color('Magenta / Fuchsia', '#ff00ff'),
  new Color('Scarlet', '#ff2400'),
  new Color('Wild Strawberry', '#ff3399'),
  new Color('Razzle Dazzle Rose', '#ff33cc'),
  new Color('Radical Red', '#ff355e'),
  new Color('Red Orange', '#ff3f34'),
  new Color('Coral Red', '#ff4040'),
  new Color('Vermilion', '#ff4d00'),
  new Color('International Orange', '#ff4f00'),
  new Color('Outrageous Orange', '#ff6037'),
  new Color('Blaze Orange', '#ff6600'),
  new Color('Pink Flamingo', '#ff66ff'),
  new Color('Orange', '#ff681f'),
  new Color('Hot Pink', '#ff69b4'),
  new Color('Persimmon', '#ff6b53'),
  new Color('Blush Pink', '#ff6fff'),
  new Color('Burning Orange', '#ff7034'),
  new Color('Pumpkin', '#ff7518'),
  new Color('Flamenco', '#ff7d07'),
  new Color('Flush Orange', '#ff7f00'),
  new Color('Coral', '#ff7f50'),
  new Color('Salmon', '#ff8c69'),
  new Color('Pizazz', '#ff9000'),
  new Color('West Side', '#ff910f'),
  new Color('Pink Salmon', '#ff91a4'),
  new Color('Neon Carrot', '#ff9933'),
  new Color('Atomic Tangerine', '#ff9966'),
  new Color('Vivid Tangerine', '#ff9980'),
  new Color('Sunshade', '#ff9e2c'),
  new Color('Orange Peel', '#ffa000'),
  new Color('Mona Lisa', '#ffa194'),
  new Color('Web Orange', '#ffa500'),
  new Color('Carnation Pink', '#ffa6c9'),
  new Color('Hit Pink', '#ffab81'),
  new Color('Yellow Orange', '#ffae42'),
  new Color('Cornflower Lilac', '#ffb0ac'),
  new Color('Sundown', '#ffb1b3'),
  new Color('My Sin', '#ffb31f'),
  new Color('Texas Rose', '#ffb555'),
  new Color('Cotton Candy', '#ffb7d5'),
  new Color('Macaroni and Cheese', '#ffb97b'),
  new Color('Selective Yellow', '#ffba00'),
  new Color('Koromiko', '#ffbd5f'),
  new Color('Amber', '#ffbf00'),
  new Color('Wax Flower', '#ffc0a8'),
  new Color('Pink', '#ffc0cb'),
  new Color('Your Pink', '#ffc3c0'),
  new Color('Supernova', '#ffc901'),
  new Color('Flesh', '#ffcba4'),
  new Color('Sunglow', '#ffcc33'),
  new Color('Golden Tainoi', '#ffcc5c'),
  new Color('Peach Orange', '#ffcc99'),
  new Color('Chardonnay', '#ffcd8c'),
  new Color('Pastel Pink', '#ffd1dc'),
  new Color('Romantic', '#ffd2b7'),
  new Color('Grandis', '#ffd38c'),
  new Color('Gold', '#ffd700'),
  new Color('School bus Yellow', '#ffd800'),
  new Color('Cosmos', '#ffd8d9'),
  new Color('Mustard', '#ffdb58'),
  new Color('Peach Schnapps', '#ffdcd6'),
  new Color('Caramel', '#ffddaf'),
  new Color('Tuft Bush', '#ffddcd'),
  new Color('Watusi', '#ffddcf'),
  new Color('Pink Lace', '#ffddf4'),
  new Color('Navajo White', '#ffdead'),
  new Color('Frangipani', '#ffdeb3'),
  new Color('Pippin', '#ffe1df'),
  new Color('Pale Rose', '#ffe1f2'),
  new Color('Negroni', '#ffe2c5'),
  new Color('Cream Brulee', '#ffe5a0'),
  new Color('Peach', '#ffe5b4'),
  new Color('Tequila', '#ffe6c7'),
  new Color('Kournikova', '#ffe772'),
  new Color('Sandy Beach', '#ffeac8'),
  new Color('Karry', '#ffead4'),
  new Color('Broom', '#ffec13'),
  new Color('Colonial White', '#ffedbc'),
  new Color('Derby', '#ffeed8'),
  new Color('Vis Vis', '#ffefa1'),
  new Color('Egg White', '#ffefc1'),
  new Color('Papaya Whip', '#ffefd5'),
  new Color('Fair Pink', '#ffefec'),
  new Color('Peach Cream', '#fff0db'),
  new Color('Lavender blush', '#fff0f5'),
  new Color('Gorse', '#fff14f'),
  new Color('Buttermilk', '#fff1b5'),
  new Color('Pink Lady', '#fff1d8'),
  new Color('Forget Me Not', '#fff1ee'),
  new Color('Tutu', '#fff1f9'),
  new Color('Picasso', '#fff39d'),
  new Color('Chardon', '#fff3f1'),
  new Color('Paris Daisy', '#fff46e'),
  new Color('Barley White', '#fff4ce'),
  new Color('Egg Sour', '#fff4dd'),
  new Color('Sazerac', '#fff4e0'),
  new Color('Serenade', '#fff4e8'),
  new Color('Chablis', '#fff4f3'),
  new Color('Seashell Peach', '#fff5ee'),
  new Color('Sauvignon', '#fff5f3'),
  new Color('Milk Punch', '#fff6d4'),
  new Color('Varden', '#fff6df'),
  new Color('Rose White', '#fff6f5'),
  new Color('Baja White', '#fff8d1'),
  new Color('Gin Fizz', '#fff9e2'),
  new Color('Early Dawn', '#fff9e6'),
  new Color('Lemon Chiffon', '#fffacd'),
  new Color('Bridal Heath', '#fffaf4'),
  new Color('Scotch Mist', '#fffbdc'),
  new Color('Soapstone', '#fffbf9'),
  new Color('Witch Haze', '#fffc99'),
  new Color('Buttery White', '#fffcea'),
  new Color('Island Spice', '#fffcee'),
  new Color('Cream', '#fffdd0'),
  new Color('Chilean Heath', '#fffde6'),
  new Color('Travertine', '#fffde8'),
  new Color('Orchid White', '#fffdf3'),
  new Color('Quarter Pearl Lusta', '#fffdf4'),
  new Color('Half and Half', '#fffee1'),
  new Color('Apricot White', '#fffeec'),
  new Color('Rice Cake', '#fffef0'),
  new Color('Black White', '#fffef6'),
  new Color('Romance', '#fffefd'),
  new Color('Yellow', '#ffff00'),
  new Color('Laser Lemon', '#ffff66'),
  new Color('Pale Canary', '#ffff99'),
  new Color('Portafino', '#ffffb4'),
  new Color('Ivory', '#fffff0'),
  new Color('White', '#ffffff'),
];
